version: "3.3"

services:
  app:
    container_name: faisals_test_blog
    build: .
    volumes:
      - ./:/usr/src
      - app-node_modules:/usr/src/node_modules
    ports:
      - 8085:8085

volumes:
  app-node_modules:
