name: Receive external requests and rebuild blog
on: repository_dispatch

jobs:
  execute-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo "Hello, I've been triggered by a webhook!"
    - run: |
        echo "Event triggered by $GITHUB_EVENT_NAME"
        echo "Dispatch type" ${{ github.event.action }}
    - if: ${{ github.event.action == 'content_preview_requested' }}
      run: echo "Got content_preview_requested"